arch:
- amd64
description: "FHEM f\xFCr HomeAssistent"
image: ghcr.io/tsoybe/ha-addon-fhem
init: false
name: FHEM
ports:
  8083/tcp: 8083
slug: fhem
url: https://github.com/tsoybe/ha-addons
usb: true
version: 0.1.10
webui: http://[HOST]:[PORT:8083]/fhem
