arch:
- amd64
description: "FHEM f\xFCr HomeAssistent"
image: ghcr.io/tsoybe/ha-addon-fhem
ingress: true
ingress_entry: fhem
ingress_port: 8084
init: false
name: FHEM
ports:
  8083/tcp: 8083
  8084/tcp: 8084
slug: fhem
uart: true
url: https://github.com/tsoybe/ha-addons
usb: true
version: 0.1.35
