arch:
- amd64
boot: auto
description: Miniflux RSS Reader
image: ghcr.io/tsoybe/ha-addon-miniflux
ingress: true
ingress_port: 8080
name: Miniflux
options:
  db_host: localhost
  db_name: miniflux
  db_password: password
  db_port: 5432
  db_user: miniflux
ports:
  8080/tcp: 8080
schema:
  db_host: str
  db_name: str
  db_password: password
  db_port: int
  db_user: str
slug: miniflux
startup: services
version: 0.1.48
