arch:
- amd64
boot: auto
description: Miniflux RSS Reader
image: ghcr.io/tsoybe/ha-addon-miniflux
init: false
name: Miniflux
description:
  admin_username: nur wenn Erstellung des Adminuser aktivert ist
  admin_password: nur wenn Erstellung des Adminuser aktivert ist
  create_admin: "Erstellung eines Adminuser aktivieren"
  db_host: Hostname oder IP des Datenbankservers
  db_port: Port der Datenbankinstanz
  db_name: Name der Datenbank
  db_user: Name des Datenbankusers
  db_password: Passwort des Datenbankusers
options:
  admin_username: admin
  admin_password: admin
  create_admin: true
  db_host: ''
  db_name: miniflux2
  db_password: miniflux
  db_port: 5432
  db_user: miniflux
ports:
  8080/tcp: 8080
schema:
  admin_username: str?
  admin_password: password?
  create_admin: bool
  db_host: str
  db_name: str
  db_password: password
  db_port: int
  db_user: str
slug: miniflux_beta
startup: services
version: 0.1.10
