arch:
- amd64
boot: auto
description: Miniflux RSS Reader
image: ghcr.io/tsoybe/ha-addon-miniflux
ingress: true
name: Miniflux
options:
  base_url: http://localhost/
  create_admin: false
  create_admin_password: password
  create_admin_username: admin
  db_host: ''
  db_name: miniflux2
  db_password: miniflux
  db_port: 5432
  db_user: miniflux
ports:
  8080/tcp: 8080
schema:
  base_url: str
  create_admin: bool
  create_admin_password: password?
  create_admin_username: str?
  db_host: str
  db_name: str
  db_password: password
  db_port: int
  db_user: str
slug: miniflux_beta
startup: services
version: 0.2.3
