name: "Miniflux"
version: "0.1.0"
slug: "miniflux"
description: "Miniflux RSS Reader"
startup: services
boot: auto
ingress: true
ingress_port: 8080
ports:
  8080/tcp: 8080
arch:
  - amd64
options:
  db_host: "localhost"
  db_port: 5432
  db_name: "miniflux"
  db_user: "miniflux"
  db_password: "password"

schema:
  db_host: str
  db_port: int
  db_name: str
  db_user: str
  db_password: password
