arch:
- amd64
description: Agent für Portainer
image: portainer/agent:lts
init: false
name: Portainer-Agent
host_network: true
docker_api: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
ports:
  1883/tcp: 1883
  9001/tcp: 9001
slug: portainer-agent
url: https://github.com/tsoybe/ha-addons
version: 0.1.14
