name: Builder

on:
  workflow_dispatch:
    inputs:
      addon:
        description: 'Addon, welches gebaut werden soll'
        required: true

jobs:

  build:
    name: Build ${{ github.event.inputs.addon }} add-on
    
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    env:
      addon: ${{ github.event.inputs.addon }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: true

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ env.addon }}"

      - name: Install semver
        run: pip install semver

      - name: Config-YAML erstellen
        shell: python
        working-directory: ${{ env.addon }}
        run: |
          import yaml
          from semver import Version
          with open('config.yaml', 'r') as file:
            config = yaml.safe_load(file)
          try:
            version = Version.parse(config.get("version", "0"), optional_minor_and_patch=True)
          except:
            version = Version.parse("0.0.0")
          version.bump_patch()
          config["version"] = version
          with open('config.yaml', 'w') as file:
            yaml.dump(config, file)

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build '${{ env.addon }}' add-on
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            --amd64 \
            --target ${{ env.addon }} \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon

      - name: Config.yaml committen und pushen
        working-directory: ${{ env.addon }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add config.yaml
          git commit -m "Versionsupdate: ${{ env.addon }}"
          git pull --rebase
          git push  
