name: Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        addon: [mqtt-anonymous]

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: true

      - name: Config-YAML erstellen
        shell: python
        working-directory: ${{ matrix.addon }}
        run: |
          import yaml
          with open('config.yaml', 'r') as file:
            config = yaml.safe_load(file)
          config["version"] = "0.1.${{ github.run_number }}"
          with open('config.yaml', 'w') as file:
            yaml.dump(config, file)

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.addon }} add-on
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            --amd64 \
            --target ${{ matrix.addon }} \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon

      - name: Config.yaml committen und pushen
        working-directory: ${{ matrix.addon }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add config.yaml
          git commit -m "Versionsupdate: ${{ matrix.addon }}"
          git push  
